apiVersion: v2
name: grafana-backup-tool
description: A Helm chart for Grafana backup tool using grafana-backup-tool
version: 0.2.0
appVersion: 'v1.6.2'
type: application

dependencies: []

keywords:
  - grafana
  - backup
  - s3
  - cronjob

maintainers:
  - name: Danila Epishev
    email: depishev@alfabank.ru
