name: Release and Build Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release-and-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            RAW_VER="${{ github.ref_name }}"
          else
            RAW_VER=$(cat VERSION)
          fi
          CLEAN_VER=$(echo $RAW_VER | sed 's/^v//')
          echo "VERSION=$CLEAN_VER" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=v${{ steps.get_version.outputs.VERSION }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
